version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
    ports:
      - "5432:5432"
    networks:
      - user_management_network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/user_management
      JWT_SECRET: newsecret
      PORT: 8080
    networks:
      - user_management_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - user_management_network
    depends_on:
      - backend

networks:
  user_management_network:
    driver: bridge
